Atualização da página do pedido
ecomplus/storefront pull request #336
Opened 2020-10-15 02:31 UTC by matheusgnreis

2020-10-30 15:12 UTC, leomp12 commented on @ecomplus/storefront-app/src/components/html/EcOrderInfo.html
> +                    class="timeline__status status"
Os class names sempre devem ter como préfixo o nome do componente (`.order-info` neste caso).

2020-10-30 15:12 UTC, leomp12 commented on @ecomplus/storefront-app/src/components/js/EcOrderInfo.js
> +    i19trackYourOrderHere: () => 'Acompanhe aqui o pedido',
`i19trackYourOrderHere` deveria ser traduzido em `'Acompanhe seu pedido aqui'`, pra ter previsibilidade as traduções do i18n devem ser exatas sempre que possível...

2020-10-30 15:12 UTC, leomp12 commented on @ecomplus/storefront-app/src/components/js/EcOrderInfo.js
> +      let c = []
`c` ? :laughing:

2020-10-30 15:12 UTC, leomp12 commented on @ecomplus/storefront-app/src/components/html/EcOrderInfo.html
> +            {{ i19trackYourOrderHere }} : <strong> {{ localOrder.number }} </strong>
Acho que o número do pedido poderia ter um destaque maior, não?

2020-10-30 15:14 UTC, leomp12 commented on @ecomplus/storefront-app/src/components/html/EcOrderInfo.html
> +        <div class="col-12">
Na verdade esses componentes deveriam estar fora dessa `.row`, em nenhum device eles fazem parte da mesma linha no grid (são sempre `.col-12`), certo?

2020-10-30 15:16 UTC, leomp12 requested changes
Faltou validar o objeto `Date` também:

![Screenshot_2020-10-30 My Shop](https://user-images.githubusercontent.com/10326572/97722702-b3024e00-1aa9-11eb-9350-50ef81596a69.png)

2020-10-31 21:38 UTC, leomp12 requested changes

2020-10-31 21:38 UTC, leomp12 commented on @ecomplus/storefront-app/src/components/html/EcOrderInfo.html
> +                      v-if="localOrder.transactions"
Não precisava checar isso porque aqui você já está em um loop no `localOrder.transactions`, se não existisse o código não chegaria neste trecho

2020-10-31 21:38 UTC, leomp12 commented on @ecomplus/storefront-app/src/components/html/EcOrderInfo.html
> -                        {{ i19FinancialStatus(financialStatus) }}
Acho que era importante manter o status atual da transação e entrega, mas caso contrário deveria ser removido o computed do JS com componente também, não só do HTML

2020-10-31 21:38 UTC, leomp12 commented on @ecomplus/storefront-app/src/components/html/EcOrderInfo.html
> +              <ul class="timeline">
Não tá legal em mobile, mesmo em desktop quando tem muitos status está ficando quebrado...

2020-10-31 21:45 UTC, leomp12 commented on @ecomplus/storefront-app/src/components/scss/EcOrderInfo.scss
> +    background: var(--light);
Aqui você meio que quis copiar os estilos do `.card` @matheusgnreis ? Na verdade o certo era usar  classe `.card` e `.card-body` mesmo, pra facilitar customização e não adicionar código desnecessário, isso vale pra outras situações deste tipo também...

2020-10-31 22:26 UTC, matheusgnreis commented on @ecomplus/storefront-app/src/components/html/EcOrderInfo.html
> +              <ul class="timeline">
Quando tem muito status ele faz o scroll lateral, não?

2020-10-31 22:28 UTC, leomp12 commented on @ecomplus/storefront-app/src/components/html/EcOrderInfo.html
> +              <ul class="timeline">
Uai aqui pra mim não, mas mesmo se fizesse não é o ideial né...

2020-10-31 22:29 UTC, leomp12 commented on @ecomplus/storefront-app/src/components/html/EcOrderInfo.html
> +              <ul class="timeline">
Principalmente em mobile

2020-11-01 05:50 UTC, leomp12 reviewed
Valeu @matheusgnreis ,
Já commitei os fixes que comentei mas seria bom dar uma olhada pras próximas...
Mudei bastante os estilos da timeline porque como estava não era responsivo, tinha como tronar reponsivo deixando parecido mas acabei fazendo de um jeito mais preguiçoso.

2020-11-01 05:50 UTC, leomp12 commented on @ecomplus/storefront-app/src/components/html/EcOrderInfo.html
> +                                  href="`${tracking.link}`"
```suggestion
                                  :href="`${tracking.link}`"
```

Faltou um `:` (ou `v-bind`) aqui...

2020-11-01 05:50 UTC, leomp12 commented on @ecomplus/storefront-app/src/components/html/EcOrderInfo.html
> +                              v-for="tracking in shippingLine.tracking_codes"
```suggestion
                              v-for="(tracking, i) in shippingLine.tracking_codes"
                              :key="`tracking-${i}`"
```

É necessário criar chaves nos loops em Vue

2020-11-01 05:50 UTC, leomp12 commented on @ecomplus/storefront-app/src/components/js/EcOrderInfo.js
> +      return d
Não estava funcionando quando o status se repetia posteriormente, por exemplo pendente -> em análise -> pendente ...

2020-11-01 05:53 UTC, leomp12 approved these changes

2020-11-01 05:53 UTC, merged

2020-11-01 21:49 UTC, matheusgnreis commented
Vou ver direitinho as mudanças que fez para puder aprender

2020-11-01 21:49 UTC, matheusgnreis commented
Valeu