ci(build-themes): setup script to build themes sass in css
ecomplus/storefront pull request #371
Opened 2020-11-30 23:02 UTC by talissonf

**Related issue**

**Summary**

**Screenshots**

**Checklist**

- [ ] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [ ] If changing UI, I've tested on most common viewports, desktop and mobile devices;

**A picture of a cute animal**

2020-11-30 23:37 UTC, leomp12 requested changes

2020-11-30 23:37 UTC, leomp12 commented on .github/workflows/build-themes.yml
> +      !contains(github.event.head_commit.message, '[skip ci]')
Não tem motivo pra executar o workflow em todo commit, só a cada release novo do Storefront, certo?

```suggestion
on: registry_package

jobs:
  build-themes:
    name: Build Storefront themes
    runs-on: ubuntu-latest
```

2020-12-01 12:19 UTC, leomp12 commented on .github/workflows/build-themes.yml
> +          BRANCH: theme-dist
```suggestion
          BRANCH: themes-dist
```

2020-12-01 12:20 UTC, leomp12 commented on .github/workflows/build-themes.yml
> +          FOLDER: .deploy
Pelo que vi no seu código, seria `.deploy/themes`, não?

2020-12-01 13:40 UTC, talissonf commented on .github/workflows/build-themes.yml
> +          FOLDER: .deploy
eu pensei q ele pegava tudo q tava dentro da pasta .deplou

2020-12-02 14:33 UTC, leomp12 commented on .github/workflows/build-themes.yml
> +          FOLDER: .deploy
Uai, no caso aqui em específico não precisa, ele iria comitar tudo dentro da pasta `themes`, acho que é desnecessário, melhor os temos todos no root do branch

2020-12-02 14:35 UTC, leomp12 approved these changes
Valeu @talissonf :+1:

2020-12-02 14:42 UTC, merged