add class to value option
ecomplus/storefront pull request #373
Opened 2020-12-02 01:52 UTC by matheusgnreis

2020-12-02 13:36 UTC, leomp12 requested changes

2020-12-02 13:36 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/ProductVariations.html
> +      :class="`variations__select--${optionText}`"
Isso aqui vai dar ruim, `optionText` nem é definido aqui ainda, é um `<select>` por grade e uma `<option>` por opção, então `optionText` só é definido no loop de `<option>`s

2020-12-02 18:29 UTC, matheusgnreis commented on @ecomplus/storefront-components/src/html/ProductVariations.html
> +      :class="`variations__select--${optionText}`"
Sim, vi agora aqui, no loop <option> nem tem classe, eu ia tirar, mas vou deixar, porque pensei em uma possibilidade que já rolou na ecomclub e que foi necessário ter isso.

2020-12-02 18:41 UTC, leomp12 requested changes

2020-12-02 18:41 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/ProductVariations.html
> +        :class="`variations__select--${optionText}`"
Então, pior que agora tem outro problema :smile: 
`variations__select` é outro elemento, temos que respeitar o [BEM](http://getbem.com/naming/):

```suggestion
        :class="`variations__select-option--${optionText}`"
```

Ou até deixamos sem classe mesmo (é meio chato estilizar `<option>` de qualquer forma):

```suggestion
```

> Até tinha comentado com você que se não tivesse classe nenhuma no `<option>` podíamos manter sem mesmo.

2020-12-04 16:48 UTC, leomp12 approved these changes

2020-12-04 16:49 UTC, merged