Popup to iframe
ecomplus/storefront pull request #398
Opened 2021-01-04 19:42 UTC by talissonf

**Related issue**

**Summary**

**Screenshots**

**Checklist**

- [ ] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [ ] If changing UI, I've tested on most common viewports, desktop and mobile devices;

**A picture of a cute animal**

2021-01-04 20:54 UTC, leomp12 requested changes

2021-01-04 20:54 UTC, leomp12 commented on @ecomplus/widget-offers-notification/src/append/product-slots.ejs
> +</style>
Isso aqui tinha que ser append no `<head>` (`head.ejs`)

2021-01-04 20:54 UTC, leomp12 commented on @ecomplus/widget-offers-notification/src/append/product-slots.ejs
> +          <div class="spinner-border spinner-border-sm" role="status" id="loading-widget">
`#loading-widget` é um ID genérico demais, tinha que ter algum prefixo tipo o ID do `<iframe>`.

2021-01-04 20:54 UTC, leomp12 commented on @ecomplus/widget-offers-notification/src/append/product-slots.ejs
> +</style>
Mas se pá nem precisa uma tag `<style>`, podia usar utility classes e inline styles mesmo

2021-01-05 14:16 UTC, talissonf commented on @ecomplus/widget-offers-notification/src/append/product-slots.ejs
> +          <div class="spinner-border spinner-border-sm" role="status" id="loading-widget">
blz

2021-01-05 14:17 UTC, talissonf commented on @ecomplus/widget-offers-notification/src/append/product-slots.ejs
> +</style>
Algumas utilities não estão funcionando, tipo border-0 w-100 h-100 🤔

2021-01-05 15:33 UTC, leomp12 commented on @ecomplus/widget-offers-notification/src/append/product-slots.ejs
> +</style>
@talissonf não usamos todas mesmo não, _bundle phobia_...
A referência está aqui https://developers.e-com.plus/storefront/@ecomplus/storefront-twbs/docs/01-components.html#utilities

2021-01-06 19:43 UTC, leomp12 commented on @ecomplus/widget-offers-notification/src/append/product-slots.ejs
> +    setTimeout(() => (document.getElementById('loading_offers_inframe').style.display = 'none'), 2000)
@talissonf já fixei mas só pra constar, no EJS não tem parse do Babel então não devemos usar ES6 em JS em tag `<script>` dentro do EJS, e essa função tinha que ter um nome mais específico também, e começando com `_` porque é interna...
Valeu!

2021-01-06 19:44 UTC, leomp12 approved these changes
Valeu @talissonf :wave:

2021-01-06 19:45 UTC, merged