feat(json+ld-product): add priceValidUntil and gtin
ecomplus/storefront pull request #515
Opened 2021-08-11 18:21 UTC by matheusgnreis

2021-08-11 18:31 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +    priceValidUntil: _.ecomUtils.onPromotion(_.state) && _.state.price_effective_date.end ? _.ecomUtils.formatDate(_.state.price_effective_date.end).replace(/(\d{2})\/(\d{2})\/(\d{4})/, '$3-$2-$1') :
```suggestion
    priceValidUntil: _.ecomUtils.onPromotion(_.state) && _.state.price_effective_date.end
      ? _.ecomUtils.formatDate(_.state.price_effective_date.end).replace(/(\d{2})\/(\d{2})\/(\d{4})/, '$3-$2-$1')
      : undefined,
```

💅🏾

2021-08-11 18:31 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +} else if(_.state.gtin && _.state.gtin[0]) {
```suggestion
} else if (_.state.gtin && _.state.gtin[0]) {
```

💅🏾

2021-08-11 18:36 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +} else if(_.state.gtin && _.state.gtin[0]) {
Era `else` mesmo? Não pode ter `mpn` e `gtin` juntos?

2021-08-11 18:39 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +    priceValidUntil: _.ecomUtils.onPromotion(_.state) && _.state.price_effective_date.end ? _.ecomUtils.formatDate(_.state.price_effective_date.end).replace(/(\d{2})\/(\d{2})\/(\d{4})/, '$3-$2-$1') :
Além da identação, acho que você não deveria usar `_.ecomUtils.formatDate` aqui, você tá formatando pra depois desformatar, e ele vai ter o retorno variado conforme a localização do cliente (seu código só funciona se a loja for pt br).

Seria mais correto (e mais performático) usar métodos do `Date` prototype, pra não precisar mexer muito na implementação atual poderia ser partindo de https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString

2021-08-11 20:14 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +} else if(_.state.gtin && _.state.gtin[0]) {
Eu fiquei nessa dúvida, porque no relatório fala mpn, ou gtin ou outro. Mas na documentação mostra dois parâmetros separados ao explicar, no exemplo mostra só um em cada (mostra um exemplo com mpn e outro com gtin)

2021-08-11 20:15 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +} else if(_.state.gtin && _.state.gtin[0]) {
Mas podemos colocar os dois, se o google gritar, a gente tira

2021-08-12 03:40 UTC, leomp12 approved these changes
Boa @matheusgnreis 👍🏾

2021-08-12 03:42 UTC, leomp12 requested changes
Aliás, deu pau 😬 
https://app.netlify.com/sites/storefront-template/deploys/611444b1e558220009568ebb#L138

> Dá pra ver nos status check da PR

2021-08-12 03:44 UTC, leomp12 requested changes

2021-08-12 03:44 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +    priceValidUntil: _.ecomUtils.onPromotion(_.state) && _.state.price_effective_date.end
```suggestion
    priceValidUntil: _.ecomUtils.onPromotion(_.state) && _.state.price_effective_date && _.state.price_effective_date.end
```

2021-08-12 18:08 UTC, leomp12 approved these changes

2021-08-12 18:09 UTC, merged