Quick Buy on Scroll
ecomplus/storefront pull request #549
Opened 2021-10-21 17:48 UTC by Suzei

**Related issue**

https://github.com/ecomplus/storefront/issues/331

**Summary**

Adds a footer on scroll, making more chances to convert 

**Screenshots**

![image](https://user-images.githubusercontent.com/55220803/138970548-1ff1496d-26ca-4568-860b-aa59285ac2b7.png)
![image](https://user-images.githubusercontent.com/55220803/138970604-9c7268e0-53a9-41d3-b0a6-80aa339cfc43.png)

**Checklist**

- [x] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [x] If changing UI, I've tested on most common viewports, desktop and mobile devices;

**A picture of a cute animal**

Frida, for my real first PR
![photo_2021-10-21_00-35-12](https://user-images.githubusercontent.com/55220803/138970617-5cfb465f-03fc-4795-99ba-c22946c9adf6.jpg)

2021-11-01 17:52 UTC, sameoldcarlos reviewed
Parece tudo certo pra mim. Deixei apenas uma sugestão de mudança 🤙

2021-11-01 17:52 UTC, sameoldcarlos commented on @ecomplus/storefront-components/src/js/TheProduct.js
Acho que a linha 507 pode ser deletada

2021-11-01 17:59 UTC, sameoldcarlos submitted a review, later dismissed
Para mim parece tudo certo 😁

2021-11-01 19:16 UTC, leomp12 requested changes

2021-11-01 19:16 UTC, leomp12 commented on @ecomplus/storefront-components/src/scss/TheProduct.scss
> +  .product__sticky-buy {
```suggestion

  .product__sticky-buy {
```

2021-11-01 19:16 UTC, leomp12 commented on @ecomplus/storefront-components/src/scss/TheProduct.scss
> +
```suggestion

```

2021-11-01 19:16 UTC, leomp12 commented on @ecomplus/storefront-components/src/scss/TheProduct.scss
> +
```suggestion
```

2021-11-01 19:16 UTC, leomp12 commented on @ecomplus/storefront-components/src/scss/TheProduct.scss
> +  @media (max-width: map-get($grid-breakpoints, md)) {
```suggestion
@media (max-width: map-get($grid-breakpoints, md)) {
```

2021-11-01 19:16 UTC, leomp12 commented on @ecomplus/storefront-components/src/scss/TheProduct.scss
> +
```suggestion
```

2021-11-01 19:16 UTC, leomp12 commented on @ecomplus/storefront-components/src/scss/TheProduct.scss
> +
```suggestion
```

2021-11-01 19:16 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/TheProduct.html
> +        class="d-flex"
```suggestion
        class="product__sticky-name"
```

2021-11-01 19:16 UTC, leomp12 commented on @ecomplus/storefront-components/src/scss/TheProduct.scss
> +    .product__sticky-buy, .product__sticky-buy-button {
```suggestion
    .product__sticky-buy,
    .product__sticky-buy-button {
```

2021-11-01 19:16 UTC, leomp12 commented on @ecomplus/storefront-components/src/scss/TheProduct.scss
> +  .product__sticky-buy {
```scss
&__sticky {
  &-buy {
    ...
  }

  &-name {
    display: flex;
  }
}
```

2021-11-01 19:16 UTC, leomp12 commented on @ecomplus/storefront-components/src/scss/TheProduct.scss
> +      padding: var(--spacer-2) var(--spacer-5) var(--spacer-2) var(--spacer-5);
```suggestion
      padding: var(--spacer-2) var(--spacer-5);
```

2021-11-01 19:16 UTC, leomp12 commented on @ecomplus/storefront-components/src/scss/TheProduct.scss
> +        padding: var(--spacer-2) var(--spacer-5);
acho que você tá repetindo isso aqui...

2021-11-01 19:16 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/TheProduct.html
> +          v-if="hasVariations || isKit"
esse v-if não deveria existir aqui, DRY

2021-11-01 19:16 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/TheProduct.html
> +          @click="goToProduct">
o método deveria adicionar direto ao carrinho se possível..

2021-11-01 19:31 UTC, leomp12 requested changes

2021-11-01 19:31 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/TheProduct.html
> +    v-if="isInStock"
```suggestion
    v-if="hasStickyBuyButton && isInStock" 
```

2021-11-01 19:31 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/TheProduct.html
> +      v-if="hasStickyBuyButton"
```js
  <transition ... >
    <div
        v-show="isStickyBuyVisible"
```

2021-11-01 19:31 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/TheProduct.js
> +      const $div = document.createElement('div')
```suggestion
      if (!this.$refs.stickyAnchor) {
        return
      }
      const $div = document.createElement('div')
```

2021-11-03 19:49 UTC, sameoldcarlos commented on @ecomplus/storefront-components/src/scss/TheProduct.scss
> +  @media (max-width: map-get($grid-breakpoints, md)) {
```suggestion
@media (max-width: map-get($grid-breakpoints, md)) {
```

2021-11-03 19:57 UTC, sameoldcarlos commented on @ecomplus/storefront-components/src/js/TheProduct.js
> +          }
```suggestion
          this.customizations[index].option = { text }
```

2021-11-03 19:59 UTC, Suzei commented on @ecomplus/storefront-components/src/html/TheProduct.html
> +      v-show="isStickyBuyVisible"
Coloquei o código do transition aí, mas não tá rolando a animação de fadeIn mesmo com o v-show com isStickyBuyVisible

2021-11-03 20:02 UTC, sameoldcarlos commented on @ecomplus/storefront-components/src/js/TheProduct.js
> +            }
```suggestion
            option: { text }
```

2021-11-03 20:48 UTC, sameoldcarlos approved these changes
Revisei e pra mim parece tudo de boa depois das alterações 🤙🏿

2021-11-04 19:07 UTC, leomp12 requested changes

2021-11-04 19:07 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/TheProduct.html
> +    v-show="body.available"
```suggestion
    v-if="hasStickyBuyButton && body.available && isInStock"
```

2021-11-04 19:07 UTC, leomp12 commented on @ecomplus/storefront-components/src/scss/TheProduct.scss
> +      display: none;
```suggestion
```

2021-11-04 19:07 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/TheProduct.js
> +      isStickyBuyVisible: true,
```suggestion
      isStickyBuyVisible: false,
```

2021-11-04 19:07 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/TheProduct.js
> +            this.$refs.stickyBox.style.display = isToVisible ? 'flex' : 'none'
```suggestion
            this.isStickyBuyVisible = isToVisible
```

2021-11-04 19:17 UTC, leomp12 requested changes

2021-11-04 19:17 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/TheProduct.js
> +
```suggestion
```

2021-11-04 19:17 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/TheProduct.js
> +      const setStickyBuyObserver = (isToVisible = true) => {
```suggestion
      let isBodyPaddingSet = false
      const setStickyBuyObserver = (isToVisible = true) => {
```

2021-11-04 19:17 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/TheProduct.js
> +            this.isStickyBuyVisible = isToVisible
```suggestion
            this.isStickyBuyVisible = isToVisible
            if (isToVisible && !isBodyPaddingSet) {
              this.$nextTick(() => {
                const stickyHeight = this.$refs.stickyBox.offsetHeight
                document.body.style.paddingBottom = `${stickyHeight}px`
              })
            }
```

2021-11-04 21:10 UTC, sameoldcarlos submitted a review, later dismissed

2021-11-05 00:35 UTC, leomp12 approved these changes
valeu galera @Suzei @sameoldcarlos 👍🏾

2021-11-05 00:35 UTC, merged