fix(APrices): check min amount from extra discount on price
ecomplus/storefront pull request #588
Opened 2021-12-24 16:53 UTC by matheusgnreis

**Related issue**
https://github.com/ecomplus/storefront/issues/587

**Solution**
![image](https://user-images.githubusercontent.com/35343551/147365647-4535eea8-4d42-4d03-ac39-f2633cd11c8a.png)

2021-12-24 17:14 UTC, leomp12 requested changes

2021-12-24 17:14 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/APrices.js
>        }
```suggestion
      if (
        this.extraDiscount.value &&
        (!this.extraDiscount.min_amount || price > this.extraDiscount.min_amount)
      ) {
        return getPriceWithDiscount(price, this.extraDiscount)
      }
```

nem sempre o desconto tem `min_amount`

2021-12-24 17:14 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/APrices.js
>        }
além disso, se o intuito é previnir descontos negativos melhor editar a função `getPriceWithDiscount`, não? garantir que ela sempre retorna um valor positivo

2021-12-24 19:52 UTC, matheusgnreis commented
Sabia que ao deletar no meu local, deletava no git nao haha. Mas ajustei ai. Deixei tbm o anterior por conta que além de sempre dar positivo, também vai aplicar na vitrine o pedido mínimo. Se não o usuário pode ver que o produto tinha ficado 1 real e ai quando vai pro checkout, não fica o preço que tinha visto e achar ruim. Por isso mantive o valor minimo pra aplicar o desconto e agora pra dar sempre positivo

2021-12-28 20:17 UTC, leomp12 reviewed
na verdade se o preço com desconto for maior que zero, retornamos zero...

2021-12-28 20:17 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/APrices.js
> +  }
```suggestion
```

2021-12-28 20:17 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/APrices.js
> +      return nonNegativeDiscount(priceWithDiscount, price)
```suggestion
      priceWithDiscount = price * (100 - value) / 100
```

2021-12-28 20:17 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/APrices.js
> +      return nonNegativeDiscount(priceWithDiscount, price)
```suggestion
      priceWithDiscount = price - value
```

2021-12-28 20:17 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/APrices.js
>      }
```suggestion
    }
    return priceWithDiscount > 0 ? priceWithDiscount : 0
```

2021-12-28 20:32 UTC, leomp12 approved these changes
value @matheusgnreis 👍🏾

2021-12-28 20:32 UTC, merged