feat(template/menu): add mega menu in desktop
ecomplus/storefront pull request #594
Opened 2021-12-30 09:44 UTC by Suzei

**Related issue**

https://github.com/ecomplus/storefront/issues/585

**Summary**

Still in progress for technical issues, i couldn't figure out how to take subcategory values to their parents-like( e.g put the value of "Notebook" and "Ultrabook" by the same line, instead of example 1 and 2) and align it. Also, it doesn't close when click outside the div

**Screenshots**

![image](https://user-images.githubusercontent.com/55220803/147739842-7b621e20-6225-4397-b512-3b4394b76d79.png)

**Checklist**

- [x] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [x] If changing UI, I've tested on most common viewports, desktop and mobile devices;

**A picture of a cute animal**

2021-12-30 19:26 UTC, leomp12 requested changes
Os comentários que eu deixei no código são de minors apenas, mas de fato a implementação está um pouco longe do issue na verdade 😬 

Não vamos ter um botão extra para o mega menu (não faz sentido), ele tem que ser renderizado no header onde já existe (configurável) uma lista de categorias principais, no hover essas categorias principais devem abrir o mega menu em vez de abrir um hamburger em desktop.

2021-12-30 19:26 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/menu.ejs
> +        >
```suggestion
        >
```

2021-12-30 19:26 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/menu.ejs
> +  </div>
tá tudo mal identado aqui 😬

2021-12-30 19:26 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/menu.ejs
> +  </div>
de qualquer forma esse trecho provavelmente nem deve existir, as categorias principais já estão listadas no header em https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-template/template/pages/%40/layout/header.ejs#L254-L264 , o mega menu deve tratar apenas as subcategorias

2022-01-10 20:23 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +               <% if (subcategory.parent?.slug !== slug) { %>
```suggestion
               <% if (!subcategory.parent || subcategory.parent.slug !== slug) { %>
```

2022-01-10 20:23 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +          <%  if (slug) { %>
```suggestion
            <%  if (slug) { %>
```

2022-01-10 20:23 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +      <% }) %>
```suggestion
            <% }) %>
            </nav>
          <% } %>
        <% }) %>
```

2022-01-10 20:23 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +    <% } %>
```suggestion
      <% } %>
```

2022-01-10 20:23 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +               <% if (subcategory.parent?.slug !== slug) { %>
aqui o build deu fatal error eu acho...

2022-01-10 20:44 UTC, Suzei commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +               <% if (subcategory.parent?.slug !== slug) { %>
nessa alteração, tu fez com que os que não tem parent não aparecessem? A gente ainda tá com esse problema, tentamos pegar o exemplo do [menu.ejs](https://github.com/ecomplus/storefront/blob/1c572289a1e06e1bf820d06113258de4ccb89b5f/%40ecomplus/storefront-template/template/pages/%40/layout/menu.ejs#L92) e a maneira que ele identifica se tem um submenu, achei que poderia fazer parecido mas não consegui
![image](https://user-images.githubusercontent.com/55220803/148836504-7e445032-a03d-49e5-82af-8683efb58056.png)

2022-01-10 20:48 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +               <% if (subcategory.parent?.slug !== slug) { %>
sim, os que não tem parentes não estarão em nenhum submenu, mas isso não resolve o print aí

2022-01-10 20:52 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +              <nav class="header__submenu" id="<%= `s-${slug.replace(/\//g, '_')}` %>">
isso aqui tá renderizando o `nav.header__submenu` em todas as categorias do header, sem verificar antes se a categoria do header tem subcategorias ou não, pra evitar que a categoria sem subcategorias tenha submenu você teria que agrupar checar antes se existe pelo menos uma subcategoria da categoria atual..

2022-01-11 20:00 UTC, Suzei commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +              <nav class="header__submenu" id="<%= `s-${slug.replace(/\//g, '_')}` %>">
quando eu tento com o .find, ele sempre retorna o primeiro valor do subcategories; no caso, eu faço um:
```
<% const hasSubmenu = ._categories.find(subcategory => subcategory.parent ) %>
```
na intenção de agrupar todos, acabo só pegando um. é a única coisa que falta pra entregar

2022-01-11 20:50 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +              <nav class="header__submenu" id="<%= `s-${slug.replace(/\//g, '_')}` %>">
sim, o método foi feito exatamente pra isso, nesse caso não use `find` 😄 
pra filtrar e não pegar só o primeiro, use https://developer.mozilla.org/pt-BR/docs/Web/JavaScript/Reference/Global_Objects/Array/filter

2022-01-11 20:53 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +              <nav class="header__submenu" id="<%= `s-${slug.replace(/\//g, '_')}` %>">
`hasSubmenu` é pra ser um boolean? se não é um boolean não deveria ser `has*`...
não acho que deveria ser tbm, acho que você deve filtrar as subcategorias e depois reutilizar já filtradas, pra evitar percorrer o array duas vezes atoa...
```ejs
<% const subcategories = _.categories.filter(/* */) %>
<% if (slug && subcategories.length) { %>
```

2022-01-13 20:56 UTC, leomp12 requested changes

2022-01-13 20:56 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +          <button
Aqui só atrapalou a indentação

2022-01-13 20:56 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +              <% const subcategories = _.categories.filter(subcategory => subcategory.parent?.slug == slug) %>
E como já conversamos antes, por compatibilidade não usem condicional chain

2022-01-13 20:56 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +                        <% if (!subcategories.parent || subcategories.parent.slug !== slug) return %>
Você já tem as subcategorias, não tem porque percorrer todas as categorias de novo e filtrar novamente da mesma forma...

2022-01-13 21:39 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +                  <a href="<%= slug %>" onmouseover="toggleSubmenu('<%= slug %>')">
Sempre vai redirecionar no clique enquanto tiver o href aqui

```suggestion
                  <a href="javascript:;" onmouseover="toggleSubmenu('<%= slug %>')" onclick="toggleSubmenu('<%= slug %>', true)">
```

2022-01-14 01:03 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/menu.js
> +    }
```suggestion
  if (isClick && slug) {
    window.location = `/${slug}`
    return
  }
  if (!isMobile) {
```

geralmente em mobile isso não vai acontecer pq os links não serão visíveis, mas se por acaso acontecer o clique devee redirecionar também...

2022-01-14 18:21 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/menu.js
> +const isOutClicked = (e) => {
`is*` é para booleanos, aqui é uma função, o ideal é o nome ser um verbo, eg.: `checkSubmenuOutClick`, também sugeri um nome menos genérico porque nesse arquivo não temos só handlers do submenu...

2022-01-14 18:21 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/menu.js
> +}
Isso aqui deveria ser só um CSS né..
Só um media query com display none

2022-01-14 18:22 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +          <button
```suggestion
        <button
```

2022-01-14 18:22 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +          </button>
```suggestion
        </button>
```

2022-01-21 18:22 UTC, leomp12 reviewed
boa, só pecaram em naming conventions agora

2022-01-21 18:22 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +                            <a class="subcategories" href="<%= subcat.slug %>">
```suggestion
                            <a class="header__submenu-subcategory" href="<%= subcat.slug %>">
```

https://en.bem.info/methodology/css/#naming

2022-01-21 18:22 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/components/_header.scss
> +    .subcategories {
```suggestion
    &-subcategory {
```

2022-01-21 18:22 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +                        <% if (!subcategory.parent || subcategories.parent.slug !==slug) return %>
```suggestion
                        <% if (!subcategory.parent || subcategories.parent.slug !== slug) return %>
```

2022-01-21 18:22 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/layout/header.ejs
> +                          <% const subcategoriesOfSub = _.categories.filter(subcat=> subcat.parent && subcat.parent.slug === subcategory.slug) %>
```suggestion
                          <% const subcategoriesOfSub = _.categories.filter(subcat => subcat.parent && subcat.parent.slug === subcategory.slug) %>
```

2022-01-21 18:22 UTC, leomp12 commented
> boa, só pecaram em naming conventions agora

quer dizer, tenho que ver se ficou bunitin ainda 😄

2022-01-24 03:03 UTC, leomp12 requested changes
na verdade o mega menu também tem que ser configurável no cms (não fica legal em todos os casos, só com uma árvore grande de categorias), desativado por padrão inclusive...

2022-01-28 23:45 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/components/_header.scss
> +  }
esse css aqui ficou inútil né?
duplicaram e foi sobrescrito depois..

2022-01-28 23:46 UTC, leomp12 approved these changes
valeu jovys @Suzei @sameoldcarlos 👍🏾

2022-01-28 23:48 UTC, merged