fix(twbs/js): jquery removal from utils
ecomplus/storefront pull request #693
Opened 2022-04-19 21:09 UTC by sameoldcarlos

**Related issue**
https://github.com/ecomplus/storefront/issues/509

**Summary**
jQuery removal from js files on storefront

**Screenshots**

**Checklist**

- [x] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [x] If changing UI, I've tested on most common viewports, desktop and mobile devices;

**A picture of a cute animal**

2022-04-19 21:15 UTC, sameoldcarlos commented
@leomp12 o caminho é esse mesmo? Mudar os arquivos que importa jQuery do twbs...

2022-04-20 03:39 UTC, leomp12 requested changes

2022-04-20 03:39 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +document.querySelector('#go-to-top').addEventListener('click', () => window.scrollTo(0, 0))
```suggestion
document.getElementById('go-to-top').addEventListener('click', () => {
  window.scroll({
    top: 0,
    behavior: 'smooth'
  })
})
```

`getElementById` é mais rápido que `querySelector`, e você estava funcionamento (a callback) aqui  também...

2022-04-20 03:39 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +  document.querySelector('.footer .collapse').style.display = 'block'
Aqui você vai mudar o funcionamento também...
Isso é um collapse (do Bootstrap), é pra abrir com um efeito de slide down, a implementação era referente ao BS4 (com jQuery), tem que ser alterada pra do BS5 https://getbootstrap.com/docs/5.1/components/collapse/#via-javascript

2022-04-20 03:42 UTC, leomp12 commented
> @leomp12 o caminho é esse mesmo? Mudar os arquivos que importam jQuery do twbs...

Acho que primeiro seria remover o jQuery do `@ecomplus/storefront-twbs` mesmo, não? E também passar a exportar no `@ecomplus/storefront-twbs` as classes que o BS5 exporta para os componentes que utilizamos, vamos precisar delas como no caso do collapse aí.

Depois disso é remover o jQuery onde tá sendo usado sim, começando pelo `@ecomplus/storefront-template` e depois verificando os outros pacotes também.

2022-04-21 20:12 UTC, leomp12 reviewed
@sameoldcarlos essa PR vai ficar enorme, não? 😬 
Eu acho que você deveria dividir as alterações em uma PR por package, uma pro `storefront-twbs` adicionando os exports, outra pro `storefront-template`, uma pra cada widget...

2022-04-21 20:12 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/fallback-404.js
> +      }</i></h3>`
Isso aqui vai renderizar o texto dentro da tag `<i>`, na verdade ele deveria ser depois do `</i>`

2022-04-21 20:12 UTC, leomp12 commented on @ecomplus/storefront-twbs/src/index.js
> +import { Collapse, Toast } from 'bootstrap'
Ou adiciona `bootstrap` nas dependências do pacote em https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-twbs/package.json#L34-L37 ou copia o source no setup assim como acontece com o SCSS https://github.com/ecomplus/storefront/blob/0fbee4eef75b0e6fd4e3d458d757d264338c5a9f/scripts/setup.js#L40-L43

Caso contrário esse import aqui pode dar BO em outros sources que importam o `@ecomplus/storefront-twbs`

2022-05-24 22:59 UTC, closed without merging