feat(themes/beauty): New beauty e-com theme
ecomplus/storefront pull request #695
Opened 2022-04-23 00:11 UTC by sameoldcarlos

**Related issue**

**Summary**
Implementation of the theme Beauty.Ecom following the [adobe xd design](https://xd.adobe.com/view/a6ede39e-9ce6-4cf7-aa10-f5cbea3d2c49-f3be/screen/b263e48d-cf5a-422c-83b9-756b79572378/).

**Screenshots**
![image](https://user-images.githubusercontent.com/7574584/164836583-f1ec0506-0198-4c29-b499-85aa7d3e2900.png)
![image](https://user-images.githubusercontent.com/7574584/164836588-734de24d-b175-43b6-acf9-4c9cac48a1f5.png)
![image](https://user-images.githubusercontent.com/7574584/164836596-3f6e9125-f395-4bf5-a4c5-cbf86d75e450.png)

**Checklist**

- [x] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [x] If changing UI, I've tested on most common viewports, desktop and mobile devices;

**A picture of a cute animal**

2022-04-26 00:33 UTC, leomp12 requested changes
Por aí @sameoldcarlos ,
Mas acho que tem pouco CSS aqui pelas alterações todas previstas no tema 🤔 
De fato no seu print eu vejo algumas diferenças, tipografia diferente em diversos elementos como o menu e info bar,  às vezes com weight diferente, às vezes parece outra fonte family...
Os breadcrumbs estão bem diferentes do protótipo, menu...

Também tem que adicionar o tema no build aqui https://github.com/ecomplus/storefront/blob/master/scripts/build-themes.js

2022-04-26 00:33 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/beauty/_variables.scss
> +$primary-dark: #e93f8e99 !default;
Isso aqui não é uma cor hexadecimal válida 😬 
Além disso, precisa mesmo forçar variações da cor primária aqui? Precisa disso pra bater algo no tema? A priori 
elas são geradas automaticamente...

2022-04-26 00:33 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/beauty/_variables.scss
> +$pink:           #e83e8d !default;
```suggestion
$pink:           #E83E8C !default;
```

É esse o padrão do tema, certo?

2022-04-26 00:33 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/beauty/_custom.scss
> +@import "variables";
```suggestion
```

Já é importado aí https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-template/template/scss/styles.scss.ejs#L10

Teria que importar aqui se fosse outro arquivo SCSS adicional, além dos `_variables.scss` e `_custom.scss` requeridos para todos os temas.

2022-04-26 00:34 UTC, leomp12 commented
Você está conseguindo ver direitinho o CSS proposto em cada elemento no Adobe XD?

2022-04-26 03:34 UTC, sameoldcarlos commented
> Por aí @sameoldcarlos , Mas acho que tem pouco CSS aqui pelas alterações todas previstas no tema 🤔 De fato no seu print eu vejo algumas diferenças, tipografia diferente em diversos elementos como o menu e info bar, às vezes com weight diferente, às vezes parece outra fonte family... Os breadcrumbs estão bem diferentes do protótipo, menu...
> 
> Também tem que adicionar o tema no build aqui https://github.com/ecomplus/storefront/blob/master/scripts/build-themes.js

A info bar precisaria de outro span no html. Como só tem um uma div pro texto em cada item, não tem como colocar as duas font-family, como no xd.
Nos breadcrumbs eu realmente não vi diferença, mas vou olhar depois..

2022-04-26 04:05 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/beauty/_custom.scss
> +  }
> A info bar precisaria de outro span no html. Como só tem um uma div pro texto em cada item, não tem como colocar as duas font-family, como no xd.

Na verdade mesmo considerando só o "título" em cada coluna na info bar, do protótipo do XD pra cá tem algumas diferenças:
- Cor da fonte;
- Tamanho da fonte;
- Itálico;
- Espessura da fonte;

![Screenshot 2022-04-26 at 01-03-13 Templates E-Com Plus](https://user-images.githubusercontent.com/10326572/165218890-15ff548a-0e13-4f57-bdf0-4259f3a5b7e3.png)

2022-05-09 21:55 UTC, leomp12 requested changes
Pode colocar aqui uns prints do tema atualizado por favor @sameoldcarlos ?
Muda o nome da pasta também para `ecom-beauty`, `new-beauty` ou algo do tipo, os temas customizados (não do Bootswatch) devem ter um hífen, virou um padrão e chego a usar isso para diferenciar em alguns casos.

2022-05-09 21:55 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/beauty/_variables.scss
> +$line-spacing-42: 42px;
Não entendi porque essas variáveis novas aqui, não é um problema mas não vi vantagem também 😐

2022-05-09 21:55 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/beauty/_variables.scss
> +$line-spacing-42: 42px;
Em geral as variáveis SCSS que o tema usa são as do próprio Bootstrap, porque alterando a variável você altera não só o CSS customizado do tempo mas também os componentes do Bootstrap.
Eventualmente pode ser útil criar variáveis SCSS pro tema também pra reutilizar algum valor, mas `$line-spacing-42` por exemplo não é uma variável SCSS que me parece útil, não vai te fazer escrever menos código e também não vai ser uma variável na prática (em nenhum caso o valor disso vai variar).

2022-05-09 21:55 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/beauty/_variables.scss
> +$primary:                  #E83E8C;
Não pode forçar a cor primária dessa forma, a secundária em alguns temas até que vai, a primária nunca.
Com isso aqui você não permite que a loja utilize a cor da sua marca, uma loja com logo azul teria todos os CTAs rosa por exemplo, seu tema seria utilizável apenas para lojas com cor azul.

2022-05-09 21:55 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/beauty/_variables.scss
> +$primary:                  #E83E8C;
O que você pode fazer é alterar a cor primária padrão do tema, usando `!default` como acontece em vários temas tipo aí https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-template/template/scss/themes/cerulean/_variables.scss#L33-L40

2022-05-11 23:33 UTC, leomp12 reviewed
E faltou adicionar o tema no CMS também

2022-05-11 23:33 UTC, leomp12 commented on scripts/build-themes.js
> +  'beauty',
```suggestion
  'ecom-beauty',
```

2022-05-11 23:34 UTC, leomp12 commented
https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/settings/general.js#L34

2022-05-11 23:48 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/ecom-beauty/_custom.scss
> +}
Por quê isso aqui?
Tá ficando um espaço em branco na home...

2022-05-11 23:48 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/ecom-beauty/_custom.scss
> +    font-family: 'Poppins';
Pelo que vi no XD ele usa Poppins como fonte padrão do corpo todo, não Roboto, aqui você tá usando Poppins só em alguns seletores então alguns textos ficam com a fonte de sistema ou Roboto, não acho que é o correto pro tema...

2022-05-11 23:48 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/ecom-beauty/_custom.scss
> +    color: $secondary;
Cor secundária em todo h4 e h6? Estranho isso em..

2022-05-11 23:48 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/ecom-beauty/_custom.scss
> +  }
Isso é pra onde no caso? A intenção é realmente sempre que for h4, h5, h6?
Se forem elementos específicos acho que seria o caso de usar seletores melhores, não utility classes...

2022-05-11 23:48 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/ecom-beauty/_custom.scss
> +    color: $secondary;
Cor secundária pra todo h1, h2 e h5? 🤔

2022-05-11 23:49 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/ecom-beauty/_custom.scss
> +    font-family: 'Poppins';
Tipo aí: 
![Screenshot 2022-05-11 at 20-48-53 My Shop](https://user-images.githubusercontent.com/10326572/167965404-da41e8f8-3eaf-4adf-827e-7922a4bd25a2.png)

2022-05-11 23:52 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/themes/ecom-beauty/_custom.scss
> +    font-family: 'Poppins';
Acho que não tá legal isso, não seria só:

```scss
main {
  font-family: 'Poppins';
  ...
```

E portanto aplicaria a fonte no conteúdo todo por padrão? E os elementos que usam a fonte cursiva (_Playfair Display_) recebem o estilo com seletores mais específicos (que já estão lá).

2022-05-14 20:20 UTC, leomp12 approved these changes
Valeu @sameoldcarlos 👍🏾 

> Acho que ainda tem umas diferenças a corrigir no CSS mesmo, mas listamos melhor e fixamos depois.

cc @vitorrgg

2022-05-14 20:22 UTC, merged

2022-05-14 20:22 UTC, leomp12 commented
> https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/settings/general.js#L34

Isso aqui também passou batido né @sameoldcarlos 🙃