feat(storefront-twbs/icons): New Feather Icons iconset
ecomplus/storefront pull request #761
Opened 2022-07-27 21:56 UTC by sameoldcarlos

**Related issue**
https://github.com/ecomplus/storefront/issues/663

**Summary**
New Feather Icons library added.

**Screenshots**
![image](https://user-images.githubusercontent.com/7574584/181379320-f349cf3b-f416-479e-a8fe-9c6b10ae4ab3.png)

**Checklist**

- [x] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [x] If changing UI, I've tested on most common viewports, desktop and mobile devices;

**A picture of a cute animal**
![image](https://user-images.githubusercontent.com/7574584/181379361-7fdf9d17-3474-4a9a-9691-528563664a36.png)

2022-07-27 22:27 UTC, leomp12 requested changes
Já dá pra a gente fazer um book dos dogs agora 😄 🐕 
Faltou isso aqui https://github.com/ecomplus/storefront/tree/master/%40ecomplus/storefront-template/template/public/assets/icons usado pro preview do CMS (faltou nas outras fontes também mas só vi agora 🙃 )

2022-07-28 18:18 UTC, sameoldcarlos commented
> Já dá pra a gente fazer um book dos dogs agora 😄 🐕 Faltou isso aqui https://github.com/ecomplus/storefront/tree/master/%40ecomplus/storefront-template/template/public/assets/icons usado pro preview do CMS (faltou nas outras fontes também mas só vi agora 🙃 )

Vou separar uma pasta no drive só com essas fotos pras PRs 😆
O das outras fontes eu crio uma PR pra cada uma ou uma só pras duas?

2022-07-28 19:01 UTC, leomp12 approved these changes
valeu @sameoldcarlos ! 👍🏾

2022-07-28 19:01 UTC, leomp12 commented
> O das outras fontes eu crio uma PR pra cada uma ou uma só pras duas?

Uai c que manda, poderia ser nessa PR de uma vez também...

2022-07-28 21:53 UTC, leomp12 approved these changes
Um comentário apenas, notei que o tabler icons é bem mais pesado né 👀

2022-07-28 21:53 UTC, merged