chore(listPayments): insert currency on list payments
ecomplus/storefront pull request #802
Opened 2022-10-24 21:13 UTC by matheusgnreis

2022-10-24 23:06 UTC, matheusgnreis commented
https://github.com/ecomplus/storefront/issues/803

2022-10-24 23:11 UTC, leomp12 requested changes
https://developers.e-com.plus/utils/module-@ecomplus_utils.html

```js
import { $ecomConfig } from '@ecomplus/utils'
```

`window.*` é má prática, último caso apenas.

2022-10-24 23:11 UTC, leomp12 commented
Esses arquivos inclusive já importam `@ecomplus/utils` ...

2022-10-24 23:18 UTC, leomp12 commented
> `window.*` é má prática, último caso apenas.

Especialmente em componentes, a ideia é reutilizar então você não sabe qual cenário ele está sendo utilizado, não sabe se `window.$ecomConfig` existe.
Se _realmente precisar_ usar uma global (o que raramente vai acontecer) fora do padrão da web (`navigator`, `location`, `document`...), precisa testar se ela existe e o componente não pode quebrar se ela não existir, tipo aí https://github.com/ecomplus/storefront/blob/8d2d46b35a6567fa2fe61b305755ca7cf8c46457/%40ecomplus/storefront-app/src/components/js/PaymentMethods.js#L63 não está estabelecendo que o `window.ecomPaymentGateways` é um array, testa se ele existe primeiro...

2022-10-24 23:19 UTC, leomp12 commented
Por último, quando você usa `window` diretamente o componente passa a não funcionar em backend (não suporta SSR), o `TheProduct` é executado em servidor, por isso:
https://github.com/ecomplus/storefront/blob/8d2d46b35a6567fa2fe61b305755ca7cf8c46457/%40ecomplus/storefront-components/src/js/TheProduct.js#L61

Sua PR quebraria isso.

2022-10-25 00:40 UTC, matheusgnreis commented
> Por último, quando você usa `window` diretamente o componente passa a não funcionar em backend (não suporta SSR), o `TheProduct` é executado em servidor, por isso:
> 
> https://github.com/ecomplus/storefront/blob/8d2d46b35a6567fa2fe61b305755ca7cf8c46457/%40ecomplus/storefront-components/src/js/TheProduct.js#L61
> 
> Sua PR quebraria isso.

Eu fiquei pensando o que poderia ser essa checagem e pensei que poderia ser algo do tipo mesmo. Valeu.

> Especialmente em componentes, a ideia é reutilizar então você não sabe qual cenário ele está sendo utilizado, não sabe se `window.$ecomConfig` existe.
> Se _realmente precisar_ usar uma global (o que raramente vai acontecer) fora do padrão da web (`navigator`, `location`, `document`...), precisa testar se ela existe e o componente não pode quebrar se ela não existir, tipo aí

Boa, valeu!

2022-10-25 20:18 UTC, leomp12 approved these changes
Só pra confirmar, de qualquer forma isso aqui só vai mandar outra currency se o produto for configurado dessa forma porque o produto (considerando o documento completo) sempre terá `currency_id` e `currency_symbol` (tem defaults pra BRL).
Ou seja, na prática se você mudar currency na config do deploy mas o produto for em BRL, isso aqui ainda vai mandar BRL, a intenção é essa mesmo né?

> Me parece que é o certo mesmo...

2022-10-25 20:23 UTC, matheusgnreis commented
Sim, o correto é cadastrar como USD, no caso, preciso colocar isso no painel, só não pensei o melhor lugar ainda.

2022-10-25 20:59 UTC, merged