feat(widget): add tiktok pixel widget
ecomplus/storefront pull request #806
Opened 2022-10-27 22:59 UTC by matheusgnreis

**Related issue**

**Summary**

**Screenshots**

**Checklist**

- [x] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [x] If changing UI, I've tested on most common viewports, desktop and mobile devices;

**A picture of a cute animal**

I only have one issue. When i try to send event search, pixel helper instead of receiving a string, they received an array. But i didnt send like ...string, to create an array. I also tried to mock a word, just like ttq.track('Search', 'bla'), and then on helper i saw an array. 
<img width="745" alt="teclado-pixel" src="https://user-images.githubusercontent.com/35343551/198412979-3587e19c-f3e4-4956-9343-7f0841078057.png">
But now i sign in into my account at tiktok and it show me that all events work perfectly:
![image](https://user-images.githubusercontent.com/35343551/198413180-96203ded-1c51-44aa-9f7d-fc8404e20bcd.png)
So, i read a little, and some people told that pixel helper didnt work so well. But if you could see, will help me a lot.

2022-10-27 22:59 UTC, matheusgnreis commented
https://github.com/ecomplus/storefront/issues/807

2022-10-28 00:21 UTC, matheusgnreis commented
Aqui não subi a alteração de colocar pacote do pixel no package.json do template, devo fazer? Se sim, preciso colocar no yourviews tbm

2022-10-28 21:29 UTC, leomp12 requested changes

2022-10-28 21:29 UTC, leomp12 commented on @ecomplus/widget-tiktok-pixel/src/lib/watch-app-routes.js
> +          })
Isso é do Facebook pra API de Conversão em backend e não tem utilidade aqui, seria só uma request a mais..

2022-10-28 21:29 UTC, leomp12 commented on @ecomplus/widget-tiktok-pixel/src/lib/watch-app-routes.js
> +      }
```suggestion
```

Pela lógica isso aqui é desnecessário, o ID é checado depois, se o ID está sendo repetido o problema teria que ser resolvido no lugar certo...

2022-10-28 21:29 UTC, leomp12 commented on @ecomplus/widget-tiktok-pixel/src/lib/watch-app-routes.js
> +          })
```suggestion
```

2022-10-28 21:29 UTC, leomp12 commented on @ecomplus/widget-tiktok-pixel/src/lib/watch-app-routes.js
> +          emitCheckout(3, 'Confirm Purchase')
Vai mandar dois eventos quando abrir o checkout, é isso mesmo?

2022-10-28 21:29 UTC, leomp12 commented on @ecomplus/widget-tiktok-pixel/src/lib/watch-app-routes.js
> +          emitCheckout(3, 'Confirm Purchase')
Você não está usando o segundo argumento no `emitCheckout`, no FB era o nome do evento, aqui do jeito que está você poderia retirar...

2022-10-28 21:29 UTC, leomp12 commented on @ecomplus/widget-tiktok-pixel/src/lib/watch-app-routes.js
> +          emitCheckout(3, 'Confirm Purchase')
```suggestion
      switch (name) {
        case 'cart':
          emitCheckout(1)
          break
        case 'checkout':
          if (!params.id) {
            emitCheckout(2)
          }
          emitCheckout(3)
```

2022-10-28 21:29 UTC, leomp12 commented on @ecomplus/widget-tiktok-pixel/src/lib/watch-app-routes.js
> +    const emitCheckout = (step, option) => {
```suggestion
    const emitCheckout = (step) => {
```

2022-10-28 21:29 UTC, leomp12 commented on @ecomplus/widget-tiktok-pixel/src/lib/watch-app-routes.js
> +            price: parseFloat(price),
Pra quê o `parseFloat`? `price` nunca vai ser uma string

2022-10-28 21:31 UTC, leomp12 commented
> Aqui não subi a alteração de colocar pacote do pixel no package.json do template, devo fazer? Se sim, preciso colocar no yourviews tbm

Sim, você importa o pacote em arquivos no source do template né, sem colocar nas dependências dá pau

2022-10-29 02:14 UTC, matheusgnreis commented on @ecomplus/widget-tiktok-pixel/src/lib/watch-app-routes.js
> +          })
Então, eu coloquei porque na api, ele pede o mesmo userAgent para ser enviado, assim como no facebook. O event id, também é enviado em alguns caso, mas talvez ele podemos retirar por hora.

2022-10-31 22:39 UTC, leomp12 commented on @ecomplus/widget-tiktok-pixel/src/lib/watch-app-routes.js
> +          })
Mas que API? Não tem app pro TikTok, então não vai ter request nenhuma em API deles em backend...

2022-10-31 22:39 UTC, leomp12 commented on @ecomplus/widget-tiktok-pixel/src/lib/watch-app-routes.js
> +          })
O user agent inclusive deve ir na request aí do Pixel client side

2022-10-31 22:46 UTC, leomp12 commented on @ecomplus/widget-tiktok-pixel/src/lib/watch-app-routes.js
> +          })
Mesmo que exista uma API do TikTok a ser consumida server side pra enviar o evento (tipo a API de conversões do Facebook), essa request só vai ter utilidade se existir um app que consuma essa informação no metadata, o que não é o caso pelo menos por enquanto.

2022-11-01 19:00 UTC, matheusgnreis commented on @ecomplus/widget-tiktok-pixel/src/lib/watch-app-routes.js
> +          })
É justamente pra isso. Eu iria colocar um app depois do tiktok, para evitar ter que na frente mudar o widget. Mas inicialmente podemos manter sem e depois fazer. No caso, precisaria ter o event_id para desduplicar depois. Então quando tiver o app, eu abro uma pr para isso

2022-11-02 01:08 UTC, leomp12 approved these changes
valeu valeu 👍🏾

2022-11-02 01:08 UTC, merged