feat(performance) : insert partytown
ecomplus/storefront pull request #853
Opened 2023-01-17 17:00 UTC by matheusgnreis

**Related issue**

**Summary**

**Screenshots**

**Checklist**

- [x] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [x] If changing UI, I've tested on most common viewports, desktop and mobile devices;

Executou partytown, gerando com type: text/partytown-x
![partytown](https://user-images.githubusercontent.com/35343551/212963133-e6574f59-29e2-485e-bfcf-f723b096f7fe.JPG)
E a request efetivada:
![partytown-1](https://user-images.githubusercontent.com/35343551/212963142-d1240fb2-df5d-412c-9fa1-fda46936533f.JPG)

2023-01-18 14:38 UTC, leomp12 commented
`feat(performance)` 😄 
Se o commit é um improve de performance seria um type `perf` , se é um type `feat` o scope não deve ter _performance_, nesse caso o repo geralmente é o pacote envolvido ...
https://www.conventionalcommits.org/en/v1.0.0/

2023-01-18 15:14 UTC, leomp12 requested changes
Esses arquivos `~partytown/**` são copiados automaticamente, deveriam estar em `.gitignore` (no root do repo) e `.npmignore` (no pacote)

2023-01-18 15:14 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/meta.ejs
> +
```suggestion
```

2023-01-18 15:14 UTC, leomp12 commented on @ecomplus/widget-tag-manager/src/append/head.ejs
> +  })(window,document,'script','<%- options.dataLayerVar %>','<%- options.gtmContainerId %>');</script>
Uai aqui você só mudou indentação (em código minificado 😄 ) , deveria estar adicionando o `type="text/partytown"` na tag script, não?

2023-01-18 15:14 UTC, leomp12 commented on package.json
> +    "@builder.io/partytown": "^0.7.4"
Isso não deveria estar nesse `package.json`, dessa forma vai funcionar só em localhost e dar pau em produção porque o pacote vai faltar

2023-01-18 15:14 UTC, leomp12 commented on package.json
> +    "@builder.io/partytown": "^0.7.4"
A dependência deve estar no `package.json` do pacote que requer ela, nesse caso o `@ecomplus/storefront-renderer` . Remove ela aqui, adiciona lá no pacote correto manualmente, depois roda `npm i` no root do repo...

2023-01-18 15:14 UTC, leomp12 commented on @ecomplus/storefront-renderer/src/renderer.js
> +
```suggestion
// insert partytown lib files for serviceworker
```

2023-01-18 15:14 UTC, leomp12 commented on @ecomplus/widget-tag-manager/src/append/head.ejs
> +  })(window,document,'script','<%- options.dataLayerVar %>','<%- options.gtmContainerId %>');</script>
https://partytown.builder.io/google-tag-manager#google-analytics-4-ga4

2023-01-18 23:12 UTC, matheusgnreis commented on @ecomplus/widget-tag-manager/src/append/head.ejs
> +  })(window,document,'script','<%- options.dataLayerVar %>','<%- options.gtmContainerId %>');</script>
Eu tinha editado ele, ai copiei o padrão do storefront de volta. Para depois fazer um para cada widget, pra não inflar uma mesma pr

2023-01-18 23:14 UTC, matheusgnreis commented on package.json
> +    "@builder.io/partytown": "^0.7.4"
> Isso não deveria estar nesse `package.json`, dessa forma vai funcionar só em localhost e dar pau em produção porque o pacote vai faltar

Beleza, valeu.

> A dependência deve estar no `package.json` do pacote que requer ela, nesse caso o `@ecomplus/storefront-renderer` . Remove ela aqui, adiciona lá no pacote correto manualmente, depois roda `npm i` no root do repo...

Top, valeu. Vou fazer.

2023-01-20 14:07 UTC, leomp12 reviewed
Evita adicionar `package-lock.json` no stage pra commit, aqui não deu conflito por sorte 🙃

2023-01-20 14:07 UTC, leomp12 commented on @ecomplus/storefront-renderer/package.json
> +    "@builder.io/partytown": "^0.7.4"
Fora de ordem, mas tá valendo...

2023-01-20 14:08 UTC, leomp12 approved these changes
👍🏾

2023-01-20 14:10 UTC, leomp12 commented
Tinha que ter tirado esses arquivos ~partytown já commitados também...

2023-01-20 14:51 UTC, merged