feat(product): add upon request and quote product
ecomplus/storefront pull request #857
Opened 2023-01-23 17:59 UTC by matheusgnreis

**Related issue**

**Summary**

**Screenshots**

Product card
![image](https://user-images.githubusercontent.com/35343551/214114123-de1aa346-4018-41fe-b8e5-16cbbd05d99e.png)
Product
![image](https://user-images.githubusercontent.com/35343551/214114376-006acf84-d290-43b6-9330-260fe8a70168.png)

**Checklist**

- [x] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [x] If changing UI, I've tested on most common viewports, desktop and mobile devices;

2023-01-24 14:39 UTC, leomp12 requested changes

2023-01-24 14:39 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/TheProduct.js
> +        }, 1000)
Bem mais fácil você setar o atributo com v-bind na verdade...

2023-01-24 14:39 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/TheProduct.js
> +        }, 1000)
Sem timeout, piorou intervalo 🙃

2023-01-24 14:39 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/ProductCard.html
> +        name="upon-request"
```suggestion
        name="price-on-request"
```

Acho que esse nome `upon-request` não diz muita coisa não...

2023-01-24 14:39 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/ProductCard.html
> +        name="upon-request"
Ou talvez:

```suggestion
        name="without-price"
```

Se pá faz mais sentido, produto sem preço não precisa ser necessariamente "sob consulta"

2023-01-24 15:11 UTC, matheusgnreis commented on @ecomplus/storefront-components/src/js/TheProduct.js
> +        }, 1000)
Precisava buscar a informação quando tivesse disponível, por isso fiz assim. No caso, coloco como prop do componente e pelo widget detalhe de produto, colocaria lá uma opção de sobconsulta e inserindo um número?

2023-01-24 15:12 UTC, matheusgnreis commented on @ecomplus/storefront-components/src/html/ProductCard.html
> +        name="upon-request"
Tinha pensado nisso também, colocar dessa forma.

2023-01-24 15:21 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/TheProduct.js
> +        }, 1000)
Coloca o link para consulta (ou número do whatsapp) como prop do componente, no source do widget (não do componente) você pode fazer essa gambiarra de query por `.whatsapp-link`, mas de qualquer forma não precisa desse set interval não...

2023-01-24 16:32 UTC, matheusgnreis commented on @ecomplus/storefront-components/src/js/TheProduct.js
> +        }, 1000)
Beleza

2023-01-25 02:03 UTC, matheusgnreis commented
Pronto

2023-01-25 19:24 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/TheProduct.html
> +                target="_blank"
```suggestion
                target="_blank"
                rel="noopener"
```

2023-01-25 19:24 UTC, leomp12 commented on @ecomplus/widget-product/src/index.js
> +      if (quoteInfo.indexOf('http') === -1) {
```suggestion
      if (quoteInfo && quoteInfo.indexOf('http') === -1) {
```

2023-01-25 19:25 UTC, leomp12 approved these changes
valeu 👍🏾 

> saí dando uns fixes aí pra agilizar o release 🙃

2023-01-25 19:26 UTC, merged