fix(the-account): remove vertical scroll and change method of insertion subscription tab
ecomplus/storefront pull request #873
Opened 2023-02-21 23:32 UTC by matheusgnreis

**Related issue**

**Summary**

**Screenshots**

**Checklist**

- [x] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [x] If changing UI, I've tested on most common viewports, desktop and mobile devices;

2023-02-22 00:11 UTC, leomp12 requested changes

2023-02-22 00:11 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/TheAccount.js
> +
`this.ecomPassport.checkAuthorization()` não retorna um objeto reativo, não vai funcionar da forma que você imaginou aqui..

2023-02-22 00:11 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/TheAccount.js
> +
Na verdade esse computed não faz diferença nenhuma, se você quer observar o login do customer precisa adicionar um:

```js
this.ecomPassport.on('login', () => {
  // ...
})
```

2023-02-22 00:11 UTC, leomp12 commented on @ecomplus/storefront-components/src/scss/TheAccount.scss
> +    overflow-y: hidden;
👍🏾

2023-02-22 00:11 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/TheAccount.js
> +
Tipo aí https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-components/src/js/PointsApplier.js#L105-L108

2023-02-22 18:33 UTC, leomp12 requested changes

2023-02-22 18:33 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/TheAccount.js
> +    })
Linkando novamente o mesmo exemplo do comentário anterior: https://github.com/ecomplus/storefront/blob/master/%40ecomplus/storefront-components/src/js/PointsApplier.js#L105-L108

Listeners precisam ser destruídos pra não gerar memory leak:

```suggestion
    this.insertSubscriptionTab()
    this.ecomPassport.on('login', this.insertSubscriptionTab)
    this.$once('hook:beforeDestroy', () => {
      this.ecomPassport.off('login', this.insertSubscriptionTab)
    })
```

2023-02-23 23:18 UTC, leomp12 approved these changes
valeu 👍🏾

2023-02-23 23:19 UTC, merged

2023-02-23 23:35 UTC, matheusgnreis commented
Eu tinha colocado assim: this.ecomPassport.on('login', this.insertSubscriptionTab) e não executava a função. Por isso coloquei:

this.ecomPassport.on('login', ()  => {
   this.insertSubscriptionTab()
})
Apesar de parecer mesma coisa..

2023-02-23 23:42 UTC, leomp12 commented
Em ambas as sintaxes a função é executada no login.
Não parece a mesma coisa e não é 😄 

Isso está errado porque você perde a referência da função e não tem como destruir o callback depois:
```js
this.ecomPassport.on('login', () => {
  this.insertSubscriptionTab()
})
```

Digita `const x = () => console.log(123); setTimeout(x, 10000);` no console e vê se em 10s não aparece o 123, não precisa (embora também funcione) de `const x = () => console.log(123); setTimeout(() => { x() }, 10000);` , o que vai mudar são os argumentos passados pra função, que nesse caso não faz diferença.

Se não funcionou no seu teste foi por algum outro motivo.