chore(buy-together): replace recommendeditems to productcard component
ecomplus/storefront pull request #881
Opened 2023-03-20 16:19 UTC by matheusgnreis

**Related issue**

Its not a issue. Just a suggestion by clients
**Summary**

Replacing recommendItems component to only productCard.
**Screenshots**

![Screenshot 2023-03-20 at 13-05-16 Caixa de Som Edifier 2 0 Bivolt (42W) R1280T Madeira](https://user-images.githubusercontent.com/35343551/226400609-a455fdb8-0f10-42ed-9610-02b2bae8d698.png)

**Checklist**

- [x] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [x] If changing UI, I've tested on most common viewports, desktop and mobile devices;

**A picture of a cute animal**

2023-03-20 18:09 UTC, leomp12 requested changes

2023-03-20 18:09 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/BuyTogether.js
> +      isLoaded: false,
Não entendi pq isso aqui

2023-03-20 19:36 UTC, matheusgnreis commented on @ecomplus/storefront-components/src/html/BuyTogether.html
> -            @recommend-items="result => recommendedItems = result.items"
Então, mas o productCard tem lá uma prop, que se isLoaded false, ele mesmo faz o fetch, não precisando de refazer esse fetch. Além disso, lá após o fetch, ele emite upload:product, dai eu busco cada fetch feito para o pai, para não precisar refazer isso direto pelo componente pai

2023-03-20 19:37 UTC, matheusgnreis commented on @ecomplus/storefront-components/src/js/BuyTogether.js
> +      isLoaded: false,
Estava dando um aviso que eu repassava essa propriedade pro filho, mas não tinha declarado.

2023-03-21 22:34 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/BuyTogether.js
> +      isLoaded: false,
Não sei que aviso você tá falando mas acho que está confundindo, esse `isLoaded` aí você não usa em lugar nenhum

2023-03-21 22:34 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/BuyTogether.html
> -            @recommend-items="result => recommendedItems = result.items"
Sim, eu sei, mas aí você vai fazer 3 requests separadas, cada uma delas retornando o produto inteiro sendo que você só precisa do item, e por fim você não escuta nenhuma delas, antes de os dados estarem prontos você já renderiza os cards e o CTA

2023-03-21 22:37 UTC, leomp12 requested changes

2023-03-21 22:37 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/BuyTogether.js
> +      }
Isso não deveria estar aqui no meio do computed, use um watch

2023-03-21 22:38 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/BuyTogether.html
> +    <slot v-if="!productIds.length"/>
Não resolve, é pra estar carregando enquanto os dados de todos os produtos não estão disponíveis, você tá mostrando os cards quando tem os IDs, não quando tem os dados dos itens pra renderizar os cards

2023-03-21 22:38 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/BuyTogether.html
> +    <slot v-if="!productIds.length"/>
Nem sempre esse fetch vai ser "instantâneo", e quando não for você cria um bug

2023-03-21 22:39 UTC, leomp12 commented on @ecomplus/storefront-components/src/html/BuyTogether.html
> +    <slot v-if="!productIds.length"/>
E `!productIds.length > 1` é `true > 1`, isso é falso sempre, na sua implementação atual na verdade não vai ter spinner em nenhum momento

2023-03-23 23:13 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/BuyTogether.js
> +      pageNumber: 1
Não faz sentido ter paginação aqui não haha

2023-03-23 23:13 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/BuyTogether.js
> +              this.hasLoadedItems = true
Não carregou ainda, você faz o fetch logo na linha abaixo

2023-03-23 23:13 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/BuyTogether.js
> +              this.hasLoadedItems = true
```suggestion
```

2023-03-23 23:13 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/BuyTogether.js
> +          this.fetchItems()
Tá fazendo requests (`this.fetchItems()`) duplicadas

2023-03-23 23:13 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/BuyTogether.js
> +    },
Não tem porque isso ser uma prop desse componente na verdade..

2023-03-23 23:13 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/BuyTogether.js
> +      }
```js
computed: {
  colClassName () {
    return `col-12 col-md-${(12 / this.items.length)} buy-together__item`
  }
}
```

Não é isso? 👀

2023-03-23 23:13 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/BuyTogether.js
> +      }
Na verdade nem precisa do computed, eu colocaria no template mesmo

2023-03-23 23:13 UTC, leomp12 commented on @ecomplus/storefront-components/src/scss/BuyTogether.scss
> +      padding-left: .5rem !important;
E não usar `!important` 🙃

2023-03-23 23:13 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/BuyTogether.js
> +      }
```vue
<div class="buy-together__item col-12" :class="`col-md-${(12 / items.length)}`">

2023-03-23 23:22 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/BuyTogether.js
> +          this.fetchItems()
Faltou um else aí no caso..

2023-03-23 23:23 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/BuyTogether.js
> +          this.fetchItems()
E notou que toda vez você repete:

```js
this.ecomSearch.setProductIds(this.productIds)
this.fetchItems()
```

?

Sua função `fetchItems` deveria conter o `this.ecomSearch.setProductIds(this.productIds)`, aí você não precisaria repetir tanto. Pela lógica nesse componente aqui o fetch é sempre pelo filtro dos `this.productIds` ...

2023-03-24 20:20 UTC, leomp12 approved these changes
valeu 👍🏾

2023-03-24 20:21 UTC, merged