chore(product/jsonld): get variation from url and set correct info in json ld
ecomplus/storefront pull request #901
Opened 2023-05-09 14:30 UTC by matheusgnreis

**Checklist**

- [x] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [x] If changing UI, I've tested on most common viewports, desktop and mobile devices;

2023-05-09 23:53 UTC, leomp12 requested changes

2023-05-09 23:53 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +      return false
```suggestion
      if (typeof window === 'object') {
        const urlParams = new URLSearchParams(window.location.search)
        const variationId = urlParams.get('variation_id')
        if (variationId) {
          return variationId
        }
      }
      return null
```

1. melhor string | null, não mistura string com boleano
2. evita fatal em node env
3. url param em geral em snake_case

2023-05-09 23:53 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +    },
```suggestion
    }
```

2023-05-09 23:53 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +    },
> não tá rodando linter né..

2023-05-09 23:53 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +     if (this.variationFromUrl && Array.isArray(this.product.variations) && this.product.variations.length) {
```suggestion
     if (this.variationFromUrl && Array.isArray(this.product.variations)) {
```

2023-05-09 23:53 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +      const selectedVariation = this.product.variations.find(variation => variation._id === this.variationFromUrl)
```js
if (selectedVariation) {
  // ..
```

o id vem de url, é bem possível que esteja errado, se estiver `selectedVariation` dá undefined e fatal aqui

2023-05-09 23:53 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +  },
esse trecho tá todo com indentação errada 🙃

2023-05-09 23:53 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +</script>
mas não era pra fazer isso aqui client side né

2023-05-09 23:53 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +</script>
JSONld é pra ser renderizado server side na real (como acontece atualmente sem essa PR), independente de JS client-side

2023-05-10 01:42 UTC, matheusgnreis commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +      return false
Valeu

2023-05-10 01:43 UTC, matheusgnreis commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +    },
![image](https://github.com/ecomplus/storefront/assets/35343551/2076d0e0-1388-4189-a938-437ab60bf1ae)
Alguma configuração adicional pra ele apontar aqui pra mim?

2023-05-10 01:52 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +</script>
Como que o json ld poderia buscar a informação do preço da variação? Porque eu consigo passar uma variavel do backend pro front, mas não consegui passar o url do parametro, vou olhar o storefront render se tem algo lá. Porque tem a variavel _.route que retorna o path, resource, mas não vem a query string junto do path

2023-05-10 01:54 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +</script>
O google até permite https://developers.google.com/search/docs/appearance/structured-data/generate-structured-data-with-javascript?hl=pt-br, mas vou tentar fazer da outra forma primeiro

2023-05-10 22:58 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +</script>
https://developers.google.com/search/docs/appearance/structured-data/generate-structured-data-with-javascript?hl=pt-br

> Outra forma de gerar dados estruturados é usar JavaScript para gerar todos os dados ou adicionar informações àqueles renderizados no servidor.

Pelo menos mantém o do servidor e só faz as alterações dinamicamente quando houver o parâmetro de URL.
Não tem como você pegar o parâmetro server side porque a página renderizada na verdade é reutilizada sem SSR a cada request, só na primeira request bate o servidor isso se ela não tiver sido pré-renderizada no build.

2023-05-11 00:27 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +</script>
Beleza, valeu

2023-05-11 00:30 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +      const selectedVariation = this.product.variations.find(variation => variation._id === this.variationFromUrl)
👀

2023-05-11 00:35 UTC, matheusgnreis commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +      const selectedVariation = this.product.variations.find(variation => variation._id === this.variationFromUrl)
eu vou mudar kk

2023-05-11 01:06 UTC, matheusgnreis commented
Mudei aqui, o ID da tag script, vi que dava na propria https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script. Dava pra fazer document.querySelector('#product-block + script[type="application/ld+json"]'), mas se alguem colocasse outro ai na frente, poderia pegar diferente, por isso coloquei id na tag

2023-05-11 01:21 UTC, leomp12 requested changes

2023-05-11 01:21 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +  const jsonLd = <%- JSON.stringify(productJsonLd) %>
Mas daí você tá duplicando isso no HTML

2023-05-11 01:21 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +  const jsonLd = <%- JSON.stringify(productJsonLd) %>
Pega esse JSON do próprio <script> que você já tá manipulando mesmo

2023-05-11 01:21 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +    const selectedVariation = variations.find(variation => variation._id === variationId)
Mesma coisa do componente Vue, não é `variations.length` que você precisa checar (desnecessário), se for array e existir um id você tenta selecionar a variação, depois você testa `if (selectedVariation) {` se a variação existe..

2023-05-11 01:21 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +    const selectedVariation = variations.find(variation => variation._id === variationId)
Aqui você vai dar fatal se vier um valor inválido (ou variação inexistente) como parâmetro de URL

2023-05-11 01:21 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +    const selectedVariation = variations.find(variation => variation._id === variationId)
E é um input de usuário então é perfeitamente factível..

2023-05-11 01:21 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +  const jsonLd = <%- JSON.stringify(productJsonLd) %>
Apenas se `if (selectedVariation) {` claro...

2023-05-11 01:21 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +  const variations = <%- JSON.stringify(_.state.variations) %>
```suggestion
  const variations = window.storefront.context.body.variations;
```

2023-05-11 01:21 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +  const variations = <%- JSON.stringify(_.state.variations) %>
Se isso der fatal por undefined bota tudo dentro de um `setTimeout(() => ..., 10)` pra executar depois de ler o DOM todo e chegar a declarar esse global

2023-05-11 01:22 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +  const variations = <%- JSON.stringify(_.state.variations) %>
Quando o JS não vai passar em bundler (tipo aqui) é mais seguro usar ; sempre

2023-05-11 01:42 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +  const jsonLd = <%- JSON.stringify(productJsonLd) %>
const urlParams = new URLSearchParams(window.location.search)
const variationId = urlParams.get('variation_id')

Beleza, entendi, só que se eu não duplicar o, onde eu vou pegar o variation da url? Porque aqui no html eu não tenho ainda o selectedVariation, só se eu colocar ele no window.selectedVariation, seria isso?

2023-05-11 01:46 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +  const variations = <%- JSON.stringify(_.state.variations) %>
Deu, tive que aumentar para 100, porque com 10 deu também algumas vezes

2023-05-11 21:49 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +            })
```suggestion
            const index = this.variationsGrids[spec].findIndex(options => options === specObject.text)
            if (index > -1) {
              this.$nextTick(() => {
                this.selectOption(specObject.text, spec, index)
              })
            }
```

2023-05-11 21:49 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +            })
E você chegou a testar isso com mais de uma grade?
Tenho minhas dúvidas aqui se vai funcionar nesse caso...

2023-05-11 21:49 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +            })
O `$nextTick` vai acabar dando no mesmo ciclo, não?

2023-05-11 21:49 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +  }, 500)
```suggestion
  }, 50)
```

2023-05-11 21:49 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +  }, 500)
Nesse delay maior sei lá se o googlebot vai esperar, de qualquer forma também não tem porque esperar 500ms aqui..

2023-05-11 22:32 UTC, leomp12 requested changes

2023-05-11 22:32 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +        }
```suggestion
        const secs = Object.keys(specifications)
        const nextSpec = (specIndex = 0) => {
          const spec = specs[specIndex]
          if (specs[specIndex] && specifications[spec] && specifications[spec].length === 1) {
            const specText  = specifications[spec][0].text
            if (this.variationsGrids[spec].find(option => option === specText)) {
              this.$nextTick(() => {
                this.selectOption(specObject.text, spec, this.orderedGrids.indexOf(spec))
                nextSpec(specIndex + 1)
              })
            }
          }
        }
        nextSpec()
```

2023-05-11 22:32 UTC, leomp12 commented on @ecomplus/storefront-components/src/js/ProductVariations.js
> +        }
Acho que tinha bastante coisa errada aí na verdade:
1. Não trata variações com duas cores (ou dois valores de uma grade qualquer), continuei não tratando mas pelo menos parei de selecionar a primeira opção (que pode ser errada) nesse caso, não seleciona nada..
2. Eu acho que não funcionaria com mais de uma grade porque você adiciona "ao mesmo tempo" vários callbacks pro próximo ciclo (`$nextTick`), na verdade teria que ser um select a cada ciclo;
3. Os argumentos de `this.selectOption` estavam errados, o terceiro argumento não é o index da opção no `variationGrids[index]`, é o index do grid https://github.com/ecomplus/storefront/blob/16e5aa5ee7b07944e5256b6e8f580ed982d55e8b/%40ecomplus/storefront-components/src/html/ProductVariations.html#L6

2023-05-11 22:35 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/product-block.ejs
> +        jsonLd.offers.price = selectedVariation.price
```suggestion
        jsonLd.sku = selectedVariation.sku
        jsonLd.offers.price = selectedVariation.price
```

SKU também, não?

2023-05-12 00:25 UTC, leomp12 approved these changes

2023-05-12 00:28 UTC, merged