feat(popup): option to insert popup after first scroll
ecomplus/storefront pull request #902
Opened 2023-05-11 03:55 UTC by matheusgnreis

**Screenshots**

![Screenshot 2023-05-11 at 00-41-05 Notebooks](https://github.com/ecomplus/storefront/assets/35343551/0cf037c6-7e3c-4980-a1a2-99854db2e88d)

**Checklist**

- [x] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [x] If changing UI, I've tested on most common viewports, desktop and mobile devices;

2023-05-13 00:06 UTC, leomp12 requested changes

2023-05-13 00:06 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/settings/info.js
Esse arquivo no CMS tem outro intuito, é pra barra de informações lá, não acho que faz muito sentido adicionar esse popup aqui

2023-05-13 00:06 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/settings/info.js
Acho que faz mais sentido em alguma config de layout, talvez no header...

2023-05-13 00:06 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/settings/info.js
> +          hint: 'Respeitar largura máxima de 600px',
Pq esse mock feio aqui?

2023-05-13 00:06 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/settings/info.js
> +        }
Não acho que precisa disso, o outro field do objeto é a imagem, se tiver imagem abre o popup...

2023-05-14 18:31 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/settings/info.js
Beleza

2023-05-14 18:41 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/settings/info.js
> +        }
beleza, feito

2023-05-16 21:41 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +})
```suggestion

if ($('#popup-modal').length) {
  $(window).one('scroll', () => {
    $('#close-modal-popup').click(() => sessionStorage.setItem('popup-modal', 'close'))
    if (!sessionStorage.getItem('popup-modal')) {
      $('#popup-modal').modal('show')
    }
  })
}
```

2023-05-16 21:47 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/layout/header.js
> +      label: 'Imagem do popup',
```suggestion
      label: 'Popup no scroll',
      hint: 'Imagem exibida em modal na primeira rolagem de página',
```

2023-05-16 21:56 UTC, leomp12 approved these changes
👍🏾 

> Acho que modal e popup são "sinônimos", então `modal-popup` me parece um nome meia bomba 🙃

2023-05-16 21:57 UTC, merged