fix(renderer): Fix url error for reverse proxy usage
ecomplus/storefront pull request #904
Opened 2023-05-17 20:59 UTC by wisley7l

2023-05-17 21:11 UTC, wisley7l commented
@leomp12 e @matheusgnreis 

Aqui a url é [reescrita aqui](https://github.com/ecomplus/storefront/blob/f02bcb51e4a63c712c20ad59dc280838b643c454/%40ecomplus/storefront-renderer/functions/index.js#L19)
com isso a url que entra na função [`proxy`](https://github.com/ecomplus/storefront/blob/f02bcb51e4a63c712c20ad59dc280838b643c454/%40ecomplus/storefront-renderer/functions/index.js#L66) não se tratava da url completa o que chega na função era apenas `/reverse-proxy/`

Em seguida ao criar um `new URL(url)` a função quebrava, dando erro `url invalid`
[Aqui](https://github.com/ecomplus/storefront/blob/f02bcb51e4a63c712c20ad59dc280838b643c454/%40ecomplus/storefront-renderer/functions/index.js#LL34C37-L34C37) acabei removendo o `headers` da requisição, pois retornava erro `403` pelo menos nos testes que executei aqui. 

E no [retorno da resposta](https://github.com/ecomplus/storefront/blob/f02bcb51e4a63c712c20ad59dc280838b643c454/%40ecomplus/storefront-renderer/functions/index.js#L70), nos meus testes, na forma anterior dava o seguinte erro `Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client`

2023-05-17 23:10 UTC, leomp12 requested changes

2023-05-17 23:10 UTC, leomp12 commented on @ecomplus/storefront-renderer/functions/index.js
> -        headers,
Ué mas tem que preservar os cabeçalhos no proxy reverso 👀

2023-05-17 23:10 UTC, leomp12 commented on @ecomplus/storefront-renderer/functions/index.js
> -        headers,
Se o cliente manda o header `X-Token` esse header tem que ser repassado pro upstream, é o que acontecia antes, não?
Se tinha algo errado nesse trecho tem que ser corrigido mantendo a função de repassar os headers originais...

2023-05-17 23:10 UTC, leomp12 commented on @ecomplus/storefront-renderer/functions/index.js
> +      proxy(req.url).then((response) => {
👍🏾

2023-05-17 23:10 UTC, leomp12 commented on @ecomplus/storefront-renderer/functions/index.js
> +            .send(data)
Não é a mesma coisa não ? 😄

2023-05-17 23:10 UTC, leomp12 commented on @ecomplus/storefront-renderer/functions/index.js
> +    const requestUrl = urlInstance.searchParams.get('url')
Que bobeira kkk

2023-05-17 23:10 UTC, leomp12 commented on @ecomplus/storefront-renderer/functions/index.js
> +    const requestUrl = urlInstance.searchParams.get('url')
👍🏾

2023-05-17 23:10 UTC, leomp12 commented on @ecomplus/storefront-renderer/functions/index.js
> +    const requestUrl = urlInstance.searchParams.get('url')
> Na real acho que nem precisava de tanto, não dá pra usar `req.query.url` ? De qualquer forma corrigindo já tá valendo...

2023-05-17 23:10 UTC, leomp12 commented on @ecomplus/storefront-renderer/functions/index.js
> +    const requestUrl = urlInstance.searchParams.get('url')
cc @matheusgnreis

2023-05-17 23:15 UTC, leomp12 commented
> Em seguida ao criar um new URL(url) a função quebrava, dando erro url invalid
[Aqui](https://github.com/ecomplus/storefront/blob/f02bcb51e4a63c712c20ad59dc280838b643c454/%40ecomplus/storefront-renderer/functions/index.js#LL34C37-L34C37) acabei removendo o headers da requisição, pois retornava erro 403 pelo menos nos testes que executei aqui.

Você poderia colocar um try/catch , mas supondo esse cenário o que sugeri pode ser melhor https://github.com/ecomplus/storefront/pull/904#discussion_r1197148640 , não precisa desse `new URL()...`, basta pegar o `req.query.url` ;

> E no [retorno da resposta](https://github.com/ecomplus/storefront/blob/f02bcb51e4a63c712c20ad59dc280838b643c454/%40ecomplus/storefront-renderer/functions/index.js#L70), nos meus testes, na forma anterior dava o seguinte erro Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client

Isso não tem relação com os headers sendo enviados ou não no proxy, isso é porque tentou responder algo na função depois de ela já ter enviado algo ao cliente (esqueça o proxy), provavelmente por causa do erro mesmo (ocorreu o erro, ela respondeu com status de erro e depois a houve algum `.send` ou coisa do tipo tentando enviar resposta novamente).

2023-05-17 23:15 UTC, leomp12 commented on @ecomplus/storefront-renderer/functions/index.js
> -        headers,
❗

2023-05-18 18:02 UTC, leomp12 commented on @ecomplus/storefront-renderer/functions/index.js
>      return null
Vai dar fatal aqui em caso de GET /reverse-proxy/ sem o URL em query string, mas acho que tudo bem...

2023-05-18 18:02 UTC, leomp12 approved these changes
Valeu 👍🏾

2023-05-18 18:02 UTC, merged