feat(multiple-shelf): multiple shelf in one shelf
ecomplus/storefront pull request #910
Opened 2023-06-02 04:20 UTC by matheusgnreis

**Screenshots**

![Screenshot 2023-06-02 at 01-10-49 My Shop](https://github.com/ecomplus/storefront/assets/35343551/31d7cfb3-cad4-494f-b462-fe4e5db938ad)
![Screenshot 2023-06-02 at 01-10-38 My Shop](https://github.com/ecomplus/storefront/assets/35343551/785d13f4-9a4e-4000-8db6-1242c310458c)

**Checklist**

- [x] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [x] If changing UI, I've tested on most common viewports, desktop and mobile devices;

**Obs [Portuguese]**

Última agência que havia feito layout da blow, sugeriu colocar dessa forma vitrine, ajudaria muito a visualização. Como tema fashion também tem essa vitrine e falta só isso pra liberar o layout, então implementei.

2023-06-02 23:50 UTC, leomp12 requested changes

2023-06-02 23:50 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +
```suggestion

```

2023-06-02 23:50 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/components/_multiple-collection-shelf.scss
> +      }
```suggestion

      li {
        min-width: 40%;
      }
```

2023-06-02 23:50 UTC, leomp12 commented on @ecomplus/storefront-template/template/scss/components/_multiple-collection-shelf.scss
> +    &__title {
```suggestion
    }

    &__title {
```

2023-06-02 23:50 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +      <% for( let index = 0; index < searchedItemsTabs.length; index++ ) { %>
```suggestion
      <% for (let index = 0; index < searchedItemsTabs.length; index++) { %>
```

2023-06-02 23:50 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +        <% for( let i = 0; i < titleTabs.length; i++ ) { %>
```suggestion
        <% for (let i = 0; i < titleTabs.length; i++) { %>
```

2023-06-02 23:50 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +        <div class="<%= index === 0 ? 'd-block ' : 'd-none ' %>collection-shelf my-lg-5" id="tab-collection-<%= index %>">
Isso aqui vai dar errado se tiver mais de um componente desse na mesma página

2023-06-02 23:50 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +        <div class="<%= index === 0 ? 'd-block ' : 'd-none ' %>collection-shelf my-lg-5" id="tab-collection-<%= index %>">
Esse id...

2023-06-02 23:50 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +                    $multipleCollection.find(`#tab-collection-${dataTab}`).toggleClass('d-block')
Isso aqui tá funcionando ? 👀

2023-06-02 23:50 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +                    $multipleCollection.find(`#tab-collection-${dataTab}`).toggleClass('d-block')
Seus ids são `tab-collection-<%= index %>`, pelo que vi não vai bater nesse `#tab-collection-${dataTab}`

2023-06-02 23:50 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +        <div class="<%= index === 0 ? 'd-block ' : 'd-none ' %>collection-shelf my-lg-5" id="tab-collection-<%= index %>">
Eu acho que você deveria criar um id antes e reutilizar nas tabs:

```js
const navId = String(Date.now())
```
```ejs
id="tab-collection-<%= navId %><%= index %>
```

2023-06-02 23:50 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +      }
O ideal seria você não fazer isso em série (um a um) na verdade

2023-06-02 23:50 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +      }
```js
const promises = []
// ...
  promises.push(/* ... */)
// ...
await Promises.all(promises)

2023-06-02 23:50 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +      }
Em série como você fez aqui é basicamente Nx mais lento, sendo N o número de tabs

2023-06-03 15:35 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +        <div class="<%= index === 0 ? 'd-block ' : 'd-none ' %>collection-shelf my-lg-5" id="tab-collection-<%= index %>">
Eu fiz teste com duas multi shelf. Eu criei um id aqui https://github.com/ecomplus/storefront/blob/multi-shelf/%40ecomplus/storefront-template/template/pages/%40/sections/multi-collection-shelf.ejs#L75, sendo um data-id genérico da multi-shelf e ai https://github.com/ecomplus/storefront/blob/multi-shelf/%40ecomplus/storefront-template/template/js/lib/utils.js#L101-L103 eu busco as informações sempre a partir desse data-id. Ou melhor mudar mesmo?

2023-06-03 15:36 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +      }
Beleza. Vou mudar aqui. Valeu.

2023-06-03 15:44 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +                    $multipleCollection.find(`#tab-collection-${dataTab}`).toggleClass('d-block')
Sim, o dataTab é o valor do index. Porque aqui https://github.com/ecomplus/storefront/blob/multi-shelf/%40ecomplus/storefront-template/template/pages/%40/sections/multi-collection-shelf.ejs#L63-L65 eu checo se existe items, e dou push dos itens e titulo para mesma posição. Titulo sempre vai ter por conta da configuração, então ao realizar push, o index da coleção, será igual ao index do titulo

2023-06-04 22:57 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +      }
Deu bom

2023-06-12 16:37 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +      }
Ideal na verdade era a request da collection também entrar aí né

2023-06-12 16:40 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +      }
E uma falha não deveria quebrar as outras

2023-06-12 16:47 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +                    $multipleCollection.find(`#tab-collection-${dataTab}`).toggleClass('d-block')
Como assim "valor do index"? Isso não tem nada a ver com o que eu falei na verdade

2023-06-12 16:54 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +                    $multipleCollection.find(`#tab-collection-${dataTab}`).toggleClass('d-block')
Vi que mudou pra classe..

2023-06-12 16:55 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +        <div class="<%= index === 0 ? 'd-block ' : 'd-none ' %>collection-shelf my-lg-5" id="tab-collection-<%= index %>">
Buscando por ID e depois por classes (não ID) filhas funciona sim..

2023-06-12 17:00 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +<% if (searchedItemsTabs && searchedItemsTabs.length && titleTabs && titleTabs.length && titleTabs.length === searchedItemsTabs.length) { %>
```suggestion
<% if (searchedItemsTabs.length && titleTabs.length === searchedItemsTabs.length) { %>
```

`searchedItemsTabs` e `titleTabs` são const e array, `!searchedItemsTabs` é impossível.
Se `searchedItemsTabs.length` e `titleTabs.length === searchedItemsTabs.length`, `!titleTabs.length` é impossível.
Muita redundância, código mais simples é mais fácil de entender e de manter

2023-06-12 17:02 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +  <div class="multiple-collection-shelf collection-shelf my-lg-5" data-id="<%= _.ecomUtils.randomObjectId() %>">
```suggestion
  <div class="multiple-collection-shelf collection-shelf my-lg-5">
```

2023-06-12 17:05 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +        const $multipleCollection = $(`.multiple-collection-shelf[data-id="${dataset.id}"]`)
```js
  $('.multiple-collection-shelf').each(function () {
    const $multipleCollection = $(this)
    // ...
  })
```

Você já tinha selecionado o elemento, pegar o ID (em dataset ou atributo ID mesmo) pra depois varrer o DOM pra pegar de novo o mesmo elemento não faz sentido...

2023-06-12 17:08 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +              if (tab.children) {
O que é possível aqui é que `tab` seja undefined, nesse caso daria fatal de qualquer forma por `chindren of undefined`, se `tab` não for undefined com certeza ela é um `HTMLElement`, e aí com certeza ela tem o array like `.children`, pode ser vazio mas a propriedade existe.
Esse `if (tab.children)` é inútil...

2023-06-12 23:36 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +                if (tab.classList) {
ok

2023-06-13 00:20 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +              if (tab.children) {
Estava dando problema com prototype entrando no for in, por isso comecei a checar, mas mudei aqui pra checar de outra forma se existe a tab.

2023-06-13 17:06 UTC, leomp12 commented on @ecomplus/storefront-template/template/pages/@/sections/multi-collection-shelf.ejs
> +    <div class="products-carousel-tabs">
Esse class name aqui não segue BEM, também não segue outra convenção, não tem relação com o componente, não segue nada 😬

2023-06-13 17:07 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +if ($('.multiple-collection-shelf').length) {
Isso aqui não gasta também..

2023-06-13 17:07 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +            }
Código repetido...

2023-06-13 17:15 UTC, leomp12 commented on @ecomplus/storefront-template/template/js/lib/utils.js
> +            }
E não tem nenhum fadezinho nem nada né

2023-06-13 18:38 UTC, leomp12 reviewed
@matheusgnreis dá uma olhada nos commits que fiz aqui por favor, as commit messages devem ajudar, verifique se comi alguma mosca quando editei e veja se segue atendendo os testes que estava fazendo aí

2023-06-14 15:12 UTC, matheusgnreis commented
Beleza, vou testar agora e ler as mensagens novas.

2023-06-14 21:15 UTC, matheusgnreis commented
Corrigi lá.
Eu evitei usar jquery desde o inicio por conta daquele trein de performance (já é importado mesmo, não fazia diferença), mas mudando tudo pra jquery economiza algumas linhas mesmo.

O título eu mantive por conta que o tema fashion tem essa opção também.

![image](https://github.com/ecomplus/storefront/assets/35343551/c83560df-29ff-409f-8d1d-1e53e4aff3a8)

No caso do blow, nem vai ter, ai só estou inserindo se tiver o titulo, não tendo, fica sem mesmo.

2023-06-14 21:24 UTC, leomp12 commented
> Eu evitei usar jquery desde o inicio por conta daquele trein de performance (já é importado mesmo, não fazia diferença), mas mudando tudo pra jquery economiza algumas linhas mesmo.

Não é isso, dava pra fazer sem jQuery também, eu mudei foi mais por causa de umas redundâncias, em especial buscando elemento sem necessidade.
Poderia fazer sem jQuery com `addEventListener` em todos os elementos, e no evento pegava o target e já sabia que era nele, não precisava buscar os elementos no DOM de novo e depois filtrar por um ID...

2023-06-14 21:27 UTC, leomp12 commented
> O título eu mantive por conta que o tema fashion tem essa opção também.

Então, eu até imaginei algo do tipo mas tinha tirado porque acho que poderia ser feito com outra seção (texto mesmo), não necessariamente seria um título dessa aí, pra evitar confusão com os títulos de cada tab e tentar resumir no CMS.
Mas tudo bem também...

2023-06-14 22:46 UTC, matheusgnreis commented
> Não é isso, dava pra fazer sem jQuery também, eu mudei foi mais por causa de umas redundâncias, em especial buscando elemento sem necessidade.
> Poderia fazer sem jQuery com `addEventListener` em todos os elementos, e no evento pegava o target e já sabia que era nele, não precisava buscar os elementos no DOM de novo e depois filtrar por um ID...

Beleza, eu vi, achava que não ia funcionar, ficou bem mais clean mesmo. Acho que agora está certo.

2023-06-14 22:57 UTC, leomp12 approved these changes
valeu 👍🏾

2023-06-14 22:58 UTC, merged