Martan
ecomplus/storefront pull request #988
Opened 2024-01-06 14:45 UTC by talissonf

**Related issue**

**Summary**

**Screenshots**

**Checklist**

- [ ] I've read and understood [contributing guidelines](https://github.com/ecomplus/storefront/blob/master/CONTRIBUTING.md);
- [ ] If changing UI, I've tested on most common viewports, desktop and mobile devices;

**A picture of a cute animal**

2024-01-06 14:46 UTC, talissonf commented
Fala @leomp12 refiz essa PR porque acabei alterando os widgets para serem parte do storefront ao invés de usar aplicacao externa atraves de iframe conforme a gente havia conversado.

Quando der faz review pra mim, com calma kkkk

2024-01-11 04:51 UTC, matheusgnreis requested changes
Precisa remover key e configurações,

2024-01-11 04:51 UTC, matheusgnreis commented on @ecomplus/storefront-template/content/widgets/martan.json
> +  "active": true,
```suggestion
  "active": false,
```
Widget precisa inicializar desativado

2024-01-11 04:51 UTC, matheusgnreis commented on @ecomplus/storefront-template/content/widgets/martan.json
> +    "martanWidgetKey": "WK_OTQ4ZWY4OTktYjUwZS01ODcwLWE4YzAtMTE4ODFkY2M2NDc0",
```suggestion
    "martanStoreId": 0,
    "martanWidgetKey": "",
```
Inicializando como widget novo

2024-01-11 04:51 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/js/lib/load-widgets.js
> +      )
```suggestion
```

2024-01-11 04:51 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/js/netlify-cms/base-config/collections/widgets.js
Já tivemos outros widgets inseridos  aqui, está um pouco desatualizado

2024-01-11 04:51 UTC, matheusgnreis commented on @ecomplus/widget-martan/cms.config.js
> +      required: true
```suggestion
      required: false
```
Enquanto a pessoa estiver editando outro widget, pode ficar apitando esse aqui, porque ele é requerido

2024-01-11 04:51 UTC, matheusgnreis commented on @ecomplus/widget-martan/cms.config.js
> +      required: true,
```suggestion
      required: false,
```

2024-01-11 04:51 UTC, matheusgnreis commented on @ecomplus/widget-martan/cms.config.js
> +      required: true,
```suggestion
      required: false,
```

2024-01-11 11:56 UTC, talissonf commented on @ecomplus/storefront-template/content/widgets/martan.json
> +  "active": true,
esse arquivo pode ser ignorado

2024-01-11 22:11 UTC, leomp12 approved these changes
Caraca tem muito trabalho aqui, boa @talissonf 👏🏾 

Os comentários são minors, IMO tá ótimo.

2024-01-11 22:11 UTC, leomp12 commented on @ecomplus/widget-martan/CHANGELOG.md
Deleta esse arquivo pra nós @talissonf

2024-01-11 22:11 UTC, leomp12 commented on @ecomplus/widget-martan/cms.config.js
> +      required: true
Tem certeza disso @matheusgnreis ?
O padrão é requerido mesmo, em quase todos os widgets os campos que são requeridos não ficam como opcionais mesmo, tipo aí https://github.com/ecomplus/storefront/blob/master/%40ecomplus/widget-tawkto/cms.config.js

2024-01-11 22:11 UTC, leomp12 commented on @ecomplus/widget-martan/cms.config.js
> +      required: true
Eu acho que aqui os fields deveriam permanecer requeridos mesmo

2024-01-12 02:31 UTC, talissonf commented
> Caraca tem muito trabalho aqui, boa @talissonf 👏🏾
> 
> Os comentários são minors, IMO tá ótimo.

Trabalheira @leomp12 mas finalmente ta saindo! Que bom que aprovou de prima <3

2024-01-12 02:33 UTC, talissonf commented
@leomp12 vou esperar retorno do @matheusgnreis pra continuar

2024-01-12 03:26 UTC, matheusgnreis commented on @ecomplus/storefront-template/template/js/lib/load-widgets.js
> +      )
O widget funciona, porém para de funcionar outras coisas, como da trustvox não se encontra ai, acabei tirando, mas depois de rodar localmente, vi que para algumas funcionalidades

2024-01-12 03:29 UTC, matheusgnreis commented
> @leomp12 vou esperar retorno do @matheusgnreis pra continuar

Pode mandar bala, depois que fiz os testes, visualizei e já removi as sugestões

2024-01-12 20:06 UTC, leomp12 commented on @ecomplus/widget-martan/cms.config.js
> +configDefault.fields.push(martan)
```
console.log({ configDefault })
```

Sobre o que estamos conversando agora a pouco @talissonf

2024-01-15 16:04 UTC, merged